[package]
name = "gif"
version = "0.1.0"
edition = "2024"

[dependencies]
abi = { path = "../../abi" }
embedded-graphics = "0.8.1"
selection_ui = { path = "../../selection_ui" }
tinygif = { git = "https://github.com/LegitCamper/tinygif" }
